### ISSUE TITLE
Cannot convert dash symbol to float while extracting gpu-usage value from job dictionary

### ISSUE THREAD

**Issue by vadimzin** [tmachnitzki/slurm_job_resource_monitor#5]
I have tried to use this tool on strand, but it doesn't work in my case. The package was installed from pip the way it is described in docs. In this particular case, I run job **without** any **gpu** being used for computations.  I suppose that sometimes gpu-usage could have symbols that cannot be converted to float. See the exception below:
```zsh
zinchenk in ~ at strand-fe1 via 🅒 hpl-torch took 2.3s …
➜ slurm_job_monitor                                       
Starting
Trial 1 / 10 failed. Retrying in 5 seconds.
Trial 2 / 10 failed. Retrying in 5 seconds.
Trial 3 / 10 failed. Retrying in 5 seconds.
Trial 4 / 10 failed. Retrying in 5 seconds.
Trial 5 / 10 failed. Retrying in 5 seconds.
Trial 6 / 10 failed. Retrying in 5 seconds.
Trial 7 / 10 failed. Retrying in 5 seconds.
Trial 8 / 10 failed. Retrying in 5 seconds.
Trial 9 / 10 failed. Retrying in 5 seconds.
Trial 10 / 10 failed. Retrying in 5 seconds.
Too many failed trials. Exiting.
Traceback (most recent call last):
  File "/gpfs/work/zinchenk/lib/miniconda3/envs/hpl-torch/bin/slurm_job_monitor", line 8, in <module>
    sys.exit(cli_entry())
  File "/gpfs/work/zinchenk/lib/miniconda3/envs/hpl-torch/lib/python3.9/site-packages/slurm_job_resource_monitor/job_monitor.py", line 491, in cli_entry
    raise exc
  File "/gpfs/work/zinchenk/lib/miniconda3/envs/hpl-torch/lib/python3.9/site-packages/slurm_job_resource_monitor/job_monitor.py", line 472, in cli_entry
    main(
  File "/gpfs/work/zinchenk/lib/miniconda3/envs/hpl-torch/lib/python3.9/site-packages/slurm_job_resource_monitor/job_monitor.py", line 437, in main
    all_jobs = dict_to_df(all_jobs)
  File "/gpfs/work/zinchenk/lib/miniconda3/envs/hpl-torch/lib/python3.9/site-packages/slurm_job_resource_monitor/job_monitor.py", line 352, in dict_to_df
    "gpu_usage": float(job_dict[node]["GPU usage"][pid][gpu_id]["sm"]),
ValueError: could not convert string to float: '-' 
```

**Comment by t-schanz** [comment]
Could you try again with the new version? Just install it again via pip or do pip install --upgrade

**Comment by t-schanz** [comment]
I think this should be solved. If not, feel free to reopen the issue.
